version: '2.1'

services:

  movie-catalog:
    container_name: movie-catalog
    image: movie-catalog
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=container
      - ASPNETCORE_URLS=http://+:4000
    ports:
      - "4000:4000"
    networks:
      - dev-network
    depends_on: 
      - mongodb
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
        interval: 1m30s
        timeout: 10s
        retries: 3  
    tty: true
    stdin_open: true

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - BUILD_CONFIG=Debug
    ports:
      - "27017:27017"
    networks:
      - dev-network
    tty: true
    stdin_open: true
    
networks:
  dev-network:
    driver: bridge
